# Generated by Django 3.1.2 on 2020-10-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20201017_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': '패스트 캠퍼스 사용자', 'verbose_name_plural': '패캠'},
        ),
        migrations.RenameField(
            model_name='test',
            old_name='phone',
            new_name='password',
        ),
    ]
