# Generated by Django 3.1.2 on 2020-10-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_auto_20201021_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Fcuser',
        ),
    ]
